apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: first-build-config
  labels:
    app: first-build-config
spec: 
  source:
    type: Git
    git: 
      uri: 
    contextDir: <folder_name>
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: ImageStreamTag
      name: <notreImage>:<tag>