apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: first-app
  labels:
    app: first-app
spec: 
  source:
    type: Git
    git: 
      uri: https://github.com/fmguyader/GitOpenshift 
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: DockerImage
      name: 'testimage:latest'